const positiveFeedback = [
  (data) => `Excellent work scoring ${data.percentage}% — you're clearly putting in the effort! Your strong grasp of ${data.strongTopics.length > 0 ? data.strongTopics.join(', ') : 'multiple topics'} shows real preparation. ${data.weakTopics.length > 0 ? `Keep an eye on ${data.weakTopics.join(', ')} to push your score even higher.` : 'No major weak spots — outstanding consistency!'} You're on the right track to ace your interviews — keep this momentum going!`,

  (data) => `${data.percentage}% is a strong score — well done! ${data.strongTopics.length > 0 ? `You demonstrated solid command over ${data.strongTopics.join(' and ')}.` : 'You showed balanced knowledge across subjects.'} ${data.weakTopics.length > 0 ? `A little more focus on ${data.weakTopics.join(', ')} and you'll be unstoppable.` : 'Keep diversifying your practice to stay sharp.'} Interviewers notice confident, well-prepared candidates — that's exactly who you're becoming.`,

  (data) => `Great job getting ${data.score} out of ${data.totalQuestions} right! ${data.strongTopics.length > 0 ? `${data.strongTopics.join(' and ')} are clearly your strengths — own them in interviews.` : 'You showed good all-round knowledge.'} ${data.weakTopics.length > 0 ? `Spend a little time reviewing ${data.weakTopics.join(', ')} and you'll have no weak spots left.` : 'Clean performance — no weak areas detected!'} Consistency like this will take you far in your placement journey.`,

  (data) => `${data.percentage}% — you're performing above average and it shows! ${data.strongTopics.length > 0 ? `Your understanding of ${data.strongTopics[0]} is particularly impressive.` : 'Your well-rounded knowledge is a real asset.'} ${data.weakTopics.length > 0 ? `${data.weakTopics.join(' and ')} still have room for improvement — a focused revision session will sort that out.` : 'No weak topics this round — exceptional!'} Keep taking quizzes like this and interview season will feel like a breeze.`,

  (data) => `Scoring ${data.percentage}% in a mixed-subject quiz is commendable — you should be proud! ${data.strongTopics.length > 0 ? `Topics like ${data.strongTopics.join(', ')} are solidly in your arsenal.` : 'You handled all subjects with confidence.'} ${data.weakTopics.length > 0 ? `Just give ${data.weakTopics.join(', ')} a bit more attention before your next attempt.` : 'Brilliant — no weak areas to report!'} You're building exactly the kind of knowledge base that impresses interviewers.`,

  (data) => `${data.score}/${data.totalQuestions} correct — that's a performance to be proud of! ${data.strongTopics.length > 0 ? `You clearly understand ${data.strongTopics.join(' and ')} at a deep level.` : 'Strong all-round performance this round.'} ${data.weakTopics.length > 0 ? `Polish your understanding of ${data.weakTopics.join(', ')} and you'll be near perfect.` : 'No gaps detected — excellent work!'} The habits you're building now will pay off massively in your interviews.`,

  (data) => `A ${data.percentage}% score puts you well ahead of the curve! ${data.strongTopics.length > 0 ? `${data.strongTopics.join(', ')} stand out as your strongest areas — interviewers will love that confidence.` : 'You showed strength across all areas.'} ${data.weakTopics.length > 0 ? `Tighten up on ${data.weakTopics.join(', ')} to become truly well-rounded.` : 'No weak topics — you are firing on all cylinders!'} Keep this pace and you'll walk into interviews with full confidence.`,

  (data) => `Well done on scoring ${data.percentage}%! ${data.strongTopics.length > 0 ? `Your mastery of ${data.strongTopics.join(' and ')} is evident and impressive.` : 'You demonstrated solid knowledge across subjects.'} ${data.weakTopics.length > 0 ? `A targeted revision of ${data.weakTopics.join(', ')} will make your preparation complete.` : 'Perfect balance across all topics!'} Remember — every quiz you take is sharpening your edge for the real interviews ahead.`,

  (data) => `${data.percentage}% — you're in strong territory! ${data.strongTopics.length > 0 ? `${data.strongTopics[0]} is clearly your comfort zone — that kind of depth is exactly what interviewers test.` : 'Consistent performance across all subjects this round.'} ${data.weakTopics.length > 0 ? `Give ${data.weakTopics.join(' and ')} one more revision pass and you'll have no vulnerabilities.` : 'No weak spots — truly impressive!'} You're making great progress — stay consistent and the results will speak for themselves.`,

  (data) => `Getting ${data.score} out of ${data.totalQuestions} right is a genuine achievement! ${data.strongTopics.length > 0 ? `Your command of ${data.strongTopics.join(', ')} would stand up well in any technical interview.` : 'Balanced and confident performance throughout.'} ${data.weakTopics.length > 0 ? `Focus next on ${data.weakTopics.join(', ')} to eliminate any remaining gaps.` : 'No weak areas — outstanding!'} The discipline you're showing in your preparation will absolutely pay off.`,

  (data) => `${data.percentage}% is a score that shows real preparation and dedication! ${data.strongTopics.length > 0 ? `You've clearly invested time in ${data.strongTopics.join(' and ')} — it shows.` : 'Strong, consistent performance across all subjects.'} ${data.weakTopics.length > 0 ? `A little more time on ${data.weakTopics.join(', ')} and your preparation will be complete.` : 'No weak spots detected — excellent work!'} Keep building on this foundation and interviews will feel like second nature.`,

  (data) => `Impressive performance — ${data.percentage}% in a mixed quiz is no small feat! ${data.strongTopics.length > 0 ? `${data.strongTopics.join(' and ')} are areas where you can answer with full confidence in interviews.` : 'You showed great breadth of knowledge this round.'} ${data.weakTopics.length > 0 ? `Revisiting ${data.weakTopics.join(', ')} once more will make your preparation airtight.` : 'Clean sweep — no weak topics!'} You're on a great trajectory — don't stop now.`,

  (data) => `${data.score}/${data.totalQuestions} — well above average and it reflects your hard work! ${data.strongTopics.length > 0 ? `Your depth in ${data.strongTopics.join(', ')} is a real competitive advantage.` : 'You covered all subjects with impressive confidence.'} ${data.weakTopics.length > 0 ? `${data.weakTopics.join(' and ')} are your next targets — address them and you'll have no blind spots.` : 'No weak areas — exceptional consistency!'} Keep this energy and interview season will be your time to shine.`,

  (data) => `A ${data.percentage}% score is a clear sign that your preparation is working! ${data.strongTopics.length > 0 ? `${data.strongTopics.join(' and ')} are locked in — that's a strong foundation.` : 'Solid knowledge across all subjects this round.'} ${data.weakTopics.length > 0 ? `Use your next session to specifically target ${data.weakTopics.join(', ')}.` : 'No weak topics — brilliant!'} Preparation like this is what separates candidates who clear interviews from those who don't.`,

  (data) => `You scored ${data.percentage}% — that's the result of genuine effort and it shows! ${data.strongTopics.length > 0 ? `Topics like ${data.strongTopics.join(', ')} are clearly well understood.` : 'Great all-round performance this quiz.'} ${data.weakTopics.length > 0 ? `Polish ${data.weakTopics.join(' and ')} and you'll have a complete, well-rounded preparation.` : 'Perfect — no gaps found!'} Stay consistent, keep quizzing, and you'll be interview-ready before you know it.`,

  (data) => `${data.percentage}% is excellent — you're clearly putting in the work! ${data.strongTopics.length > 0 ? `Your knowledge of ${data.strongTopics.join(' and ')} is a genuine strength to leverage in interviews.` : 'Impressive consistency across all areas.'} ${data.weakTopics.length > 0 ? `One focused revision session on ${data.weakTopics.join(', ')} and you'll be truly unstoppable.` : 'No weaknesses detected — outstanding!'} This kind of preparation is what top companies look for in candidates.`,

  (data) => `Great score — ${data.score} out of ${data.totalQuestions}! ${data.strongTopics.length > 0 ? `You clearly have ${data.strongTopics.join(' and ')} mastered — that confidence will carry you far.` : 'Consistent and confident performance throughout.'} ${data.weakTopics.length > 0 ? `Just shore up ${data.weakTopics.join(', ')} and your preparation will be complete.` : 'No weak areas — well done!'} Keep taking quizzes regularly and you'll walk into every interview fully prepared.`,

  (data) => `${data.percentage}% — you should feel good about this performance! ${data.strongTopics.length > 0 ? `${data.strongTopics.join(', ')} are clearly areas you can answer without hesitation.` : 'You showed great depth across all subjects.'} ${data.weakTopics.length > 0 ? `Target ${data.weakTopics.join(' and ')} in your next session to close any remaining gaps.` : 'No weak spots — truly impressive preparation!'} The work you're putting in now will absolutely make a difference when it matters most.`,

  (data) => `Scoring ${data.percentage}% shows you are well on your way to being interview-ready! ${data.strongTopics.length > 0 ? `Your grasp of ${data.strongTopics.join(' and ')} is clearly solid.` : 'You performed consistently well across all topics.'} ${data.weakTopics.length > 0 ? `Give ${data.weakTopics.join(', ')} a focused revision and you'll have no weak points left.` : 'No weak areas — exceptional!'} Keep this momentum going and interviews will feel manageable and even exciting.`,

  (data) => `${data.score}/${data.totalQuestions} correct — a performance that reflects real preparation! ${data.strongTopics.length > 0 ? `${data.strongTopics.join(' and ')} are areas where you can answer with full confidence.` : 'Strong knowledge across all subjects this round.'} ${data.weakTopics.length > 0 ? `A quick revision of ${data.weakTopics.join(', ')} will make your preparation complete.` : 'No weak spots — fantastic work!'} You're building the right habits — stay consistent and success will follow.`,
];

const negativeFeedback = [
  (data) => `You scored ${data.percentage}% this round — don't be disheartened, every expert started exactly where you are now. ${data.weakTopics.length > 0 ? `Topics like ${data.weakTopics.join(', ')} need focused attention — go back to their core concepts.` : 'Review all topics systematically to build a stronger foundation.'} ${data.strongTopics.length > 0 ? `You did show promise in ${data.strongTopics.join(' and ')} — build on those wins.` : 'Every quiz attempt is teaching you something valuable.'} Hard work compounds — keep going and the scores will follow.`,

  (data) => `${data.score} out of ${data.totalQuestions} this time — the gap between where you are and where you want to be is closed by consistent effort. ${data.weakTopics.length > 0 ? `${data.weakTopics.join(', ')} are clearly areas that need work — dedicate focused time to each.` : 'A systematic review of all subjects will help strengthen your foundation.'} ${data.strongTopics.length > 0 ? `Your performance in ${data.strongTopics.join(' and ')} shows you have the capability — apply that same focus everywhere.` : 'Each attempt is building your pattern recognition.'} Don't give up — the improvement will come.`,

  (data) => `A ${data.percentage}% score tells you where to direct your energy next. ${data.weakTopics.length > 0 ? `Start with ${data.weakTopics[0]} — understand the fundamentals before moving to advanced concepts.` : 'Go back to basics across all subjects and rebuild from there.'} ${data.strongTopics.length > 0 ? `${data.strongTopics.join(' and ')} are bright spots — proof that your effort is working in some areas.` : 'Every question you got wrong is a lesson — review each explanation carefully.'} The candidates who improve fastest are the ones who learn from every attempt.`,

  (data) => `${data.percentage}% — this is not where you want to be, but it IS where your improvement journey begins. ${data.weakTopics.length > 0 ? `${data.weakTopics.join(', ')} need serious attention — consider spending at least 30 minutes on each topic.` : 'Review every subject systematically and focus on understanding, not memorizing.'} ${data.strongTopics.length > 0 ? `You got ${data.strongTopics.join(' and ')} right — that shows you can do this.` : 'Read each explanation carefully and take notes on what you got wrong.'} Hard work and consistency will get you where you want to go.`,

  (data) => `Getting ${data.score}/${data.totalQuestions} right means there's significant room to grow — and that's actually an opportunity. ${data.weakTopics.length > 0 ? `Focus your next study session entirely on ${data.weakTopics.join(' and ')}.` : 'A full review of all topics will give you the foundation you need.'} ${data.strongTopics.length > 0 ? `Your correct answers in ${data.strongTopics.join(', ')} show your preparation is starting to work — just keep going.` : 'Take time to understand the explanations for every wrong answer.'} The only way is up — keep pushing.`,

  (data) => `${data.percentage}% this round — interviews test exactly these concepts so now is the time to strengthen your foundation. ${data.weakTopics.length > 0 ? `${data.weakTopics.join(', ')} are your priority areas — don't move on until you understand them deeply.` : 'Start from scratch on the topics you struggled with and build upwards.'} ${data.strongTopics.length > 0 ? `The fact that you got ${data.strongTopics.join(' and ')} right means you have the capability to improve across the board.` : 'Every correct answer builds confidence — celebrate small wins while working on the gaps.'} Struggle now, succeed in interviews — keep going.`,

  (data) => `A score of ${data.percentage}% shows there's work to be done — and the good news is you've already identified exactly what that work is. ${data.weakTopics.length > 0 ? `Make a study plan targeting ${data.weakTopics.join(', ')} — even 20 minutes a day will make a huge difference.` : 'Create a systematic study plan covering all subjects before your next attempt.'} ${data.strongTopics.length > 0 ? `Your understanding of ${data.strongTopics.join(' and ')} is a positive sign — build on those strengths.` : 'Review every explanation thoroughly and quiz yourself again tomorrow.'} Improvement is not instant but it is inevitable with consistent effort.`,

  (data) => `${data.score}/${data.totalQuestions} — this score is feedback, not failure. It's telling you exactly where to focus. ${data.weakTopics.length > 0 ? `${data.weakTopics.join(' and ')} need the most attention right now — go deep on these topics.` : 'Review each subject from its core fundamentals before attempting again.'} ${data.strongTopics.length > 0 ? `You showed strength in ${data.strongTopics.join(', ')} — that's real progress worth acknowledging.` : 'Every attempt is building your knowledge base, even when it doesn\'t feel like it.'} Stay determined — the gap between this score and a great score is just focused study.`,

  (data) => `${data.percentage}% this round — technical interviews are tough and every candidate struggles at this stage. ${data.weakTopics.length > 0 ? `Prioritize ${data.weakTopics.join(', ')} — understand why each wrong answer was wrong before moving forward.` : 'Go back to each topic and study the fundamentals without rushing.'} ${data.strongTopics.length > 0 ? `You got ${data.strongTopics.join(' and ')} right — that foundation matters more than you think.` : 'Read every explanation, take notes, and come back stronger tomorrow.'} The candidates who push through this phase are the ones who make it — be one of them.`,

  (data) => `Scoring ${data.percentage}% means you have clear targets for improvement — which is actually more useful than a vague sense that something is wrong. ${data.weakTopics.length > 0 ? `Your immediate focus should be ${data.weakTopics.join(' and ')} — understand each concept from first principles.` : 'Go topic by topic and rebuild your understanding methodically.'} ${data.strongTopics.length > 0 ? `Your grasp of ${data.strongTopics.join(', ')} is already solid — now bring the other topics up to that same level.` : 'Use each wrong answer as a study guide for your next session.'} Consistent effort over time always beats talent — keep working.`,

  (data) => `${data.score} correct out of ${data.totalQuestions} — you're in the building phase of your preparation and that's okay. ${data.weakTopics.length > 0 ? `Take ${data.weakTopics.join(', ')} one at a time — deep understanding of each concept is more valuable than surface-level coverage of many.` : 'A structured, topic-by-topic review will transform your scores quickly.'} ${data.strongTopics.length > 0 ? `The fact that you got ${data.strongTopics.join(' and ')} right shows your efforts are producing results.` : 'Every quiz you take is making you more familiar with these concepts.'} Don't compare your chapter one to someone else's chapter ten — just keep going.`,

  (data) => `${data.percentage}% — the road to interview success runs straight through moments like this one. ${data.weakTopics.length > 0 ? `Use your weak topics — ${data.weakTopics.join(', ')} — as your study roadmap for the next few days.` : 'Review all topics carefully and focus on truly understanding rather than memorizing.'} ${data.strongTopics.length > 0 ? `You showed real knowledge in ${data.strongTopics.join(' and ')} — that's not nothing, that's a start.` : 'Every session is adding to your knowledge base even when progress feels slow.'} Hard work today means confidence in the interview room tomorrow.`,

  (data) => `Getting ${data.score}/${data.totalQuestions} right this round — everyone who is interview-ready today was once at this exact score. ${data.weakTopics.length > 0 ? `Write down ${data.weakTopics.join(' and ')} and make them your mission for the next study session.` : 'Take each topic systematically and don\'t rush the process.'} ${data.strongTopics.length > 0 ? `Your performance on ${data.strongTopics.join(', ')} is a reminder that you can understand these concepts — now apply that to everything else.` : 'Review each wrong answer carefully — the explanations are your best teacher right now.'} Progress is rarely linear — stay consistent and trust the process.`,

  (data) => `A ${data.percentage}% score is a starting point, not an ending point. ${data.weakTopics.length > 0 ? `${data.weakTopics.join(', ')} are the areas holding your score back — attack them directly.` : 'A comprehensive review of all topics will lay the groundwork for rapid improvement.'} ${data.strongTopics.length > 0 ? `You got ${data.strongTopics.join(' and ')} right — proof that your preparation can produce results.` : 'Use the explanations for every wrong answer as mini study lessons.'} The difference between where you are and where you want to be is measured in focused study sessions — start today.`,

  (data) => `${data.percentage}% this time — technical knowledge takes time to build and you're in the middle of that process. ${data.weakTopics.length > 0 ? `Target ${data.weakTopics.join(' and ')} specifically in your next study session — understand the why behind every concept.` : 'Study each subject systematically and test yourself frequently.'} ${data.strongTopics.length > 0 ? `Your correct answers in ${data.strongTopics.join(', ')} show real understanding — replicate that focus across other topics.` : 'Don\'t skip the explanations — they are more valuable than the questions themselves.'} Every session makes you stronger — don't stop.`,

  (data) => `${data.score} out of ${data.totalQuestions} — low scores on practice quizzes are exactly how you avoid low scores in real interviews. ${data.weakTopics.length > 0 ? `${data.weakTopics.join(', ')} are your priority — revisit their core definitions and then practice application.` : 'Cover all subjects methodically — no shortcuts at this stage.'} ${data.strongTopics.length > 0 ? `You showed understanding in ${data.strongTopics.join(' and ')} — that's the kind of knowledge that compounds over time.` : 'Study the explanations deeply — they contain everything you need to improve.'} Keep going — the effort you put in today is the confidence you'll have on interview day.`,

  (data) => `${data.percentage}% — there's a gap between your current knowledge and interview-readiness, but it's absolutely closeable. ${data.weakTopics.length > 0 ? `Make a focused plan for ${data.weakTopics.join(', ')} — spend quality time on each before your next quiz.` : 'Review the fundamentals of every subject and rebuild your understanding from the ground up.'} ${data.strongTopics.length > 0 ? `${data.strongTopics.join(' and ')} are already in your toolkit — add to them every day.` : 'Every wrong answer today is a right answer waiting to happen tomorrow.'} The gap closes one study session at a time — keep putting them in.`,

  (data) => `Scoring ${data.percentage}% shows you have significant learning ahead — and the good news is you've started. ${data.weakTopics.length > 0 ? `Focus intensively on ${data.weakTopics.join(' and ')} — these are the concepts that will come up in interviews.` : 'Build a structured study schedule and tackle each topic one at a time.'} ${data.strongTopics.length > 0 ? `Your performance in ${data.strongTopics.join(', ')} gives you a base to build from.` : 'Take your time with the explanations — understanding is more powerful than memorization.'} Slow progress is still progress — show up every day and you will get there.`,

  (data) => `${data.score}/${data.totalQuestions} this round — the interview journey is tough but you're already further than those who haven't started. ${data.weakTopics.length > 0 ? `${data.weakTopics.join(', ')} need the most work — be honest with yourself and dedicate real time to them.` : 'Go back to basics across all subjects and build your knowledge layer by layer.'} ${data.strongTopics.length > 0 ? `Your correct answers in ${data.strongTopics.join(' and ')} show that your efforts are working — scale that approach to other topics.` : 'Review every explanation and ask yourself if you truly understand the concept, not just the answer.'} Keep pushing — the transformation happens in the sessions where you feel like quitting.`,

  (data) => `${data.percentage}% — this score is information, and that information is pointing you directly at what to study next. ${data.weakTopics.length > 0 ? `Put ${data.weakTopics.join(' and ')} at the top of your study list and don't move on until you can explain them clearly.` : 'Work through each subject from fundamentals to advanced concepts without skipping steps.'} ${data.strongTopics.length > 0 ? `You got ${data.strongTopics.join(', ')} right — that's evidence that you can learn this material.` : 'Use every wrong answer as motivation to study harder and smarter.'} The candidates who treat every low score as a lesson are the ones who end up with offers.`,
];

const feedtemp = (data) => {
  if (data.percentage >= 50) {
    const index = (data.attemptIndex || 0) % positiveFeedback.length;
    return positiveFeedback[index](data);
  } else {
    const index = (data.attemptIndex || 0) % negativeFeedback.length;
    return negativeFeedback[index](data);
  }
};

export default feedtemp;