const feedtemp = [
  (data) => `You scored ${data.percentage}% in this round — ${data.percentage >= 70 ? 'a solid performance!' : 'there\'s room to grow!'} Your strongest area was ${data.strongTopics.length > 0 ? data.strongTopics[0] : 'yet to be determined'} where you showed confident understanding. On the flip side, ${data.weakTopics.length > 0 ? data.weakTopics.join(', ') : 'no major weak spots'} need more attention. Keep a consistent practice routine and you\'ll see improvement quickly.`,

  (data) => `This attempt shows you got ${data.score} out of ${data.totalQuestions} questions right. ${data.weakTopics.length > 0 ? `Topics like ${data.weakTopics.join(' and ')} are pulling your score down — revisit their fundamentals.` : 'No major weak topics this round — great consistency!'} ${data.strongTopics.length > 0 ? `You clearly have a good grip on ${data.strongTopics.join(', ')}.` : ''} Focus on quality over speed in your next attempt.`,

  (data) => `A ${data.percentage}% score tells an interesting story. ${data.strongTopics.length > 0 ? `You nailed ${data.strongTopics.join(' and ')} — that confidence will serve you well in interviews.` : 'Build consistency across subjects before your next quiz.'} ${data.weakTopics.length > 0 ? `However, ${data.weakTopics.join(', ')} still need work — try solving 5 focused questions on each before your next quiz.` : 'Keep up the clean performance!'} Every quiz is one step closer to interview-ready.`,

  (data) => `You answered ${data.score}/${data.totalQuestions} correctly this session. ${data.percentage >= 70 ? 'You\'re in strong territory — this score would hold up well in a real interview setting.' : 'Don\'t be discouraged — every attempt builds your pattern recognition.'} ${data.weakTopics.length > 0 ? `Spend extra time on ${data.weakTopics[0]} — it appeared as your weakest link this round.` : 'No glaring weak spots — keep diversifying your practice.'} Consistency is the key to cracking technical interviews.`,

  (data) => `${data.percentage}% — ${data.percentage >= 80 ? 'Excellent work!' : data.percentage >= 50 ? 'Decent effort!' : 'Keep pushing!'} ${data.strongTopics.length > 0 ? `Your understanding of ${data.strongTopics.join(', ')} is clearly solid.` : 'Work on building at least one strong subject area.'} ${data.weakTopics.length > 0 ? `The concepts in ${data.weakTopics.join(', ')} are worth revisiting — try explaining them out loud to test your understanding.` : 'No weak topics detected this round!'} The best preparation is regular, varied practice.`,

  (data) => `This round you got ${data.score} correct out of ${data.totalQuestions}. ${data.weakTopics.length > 0 ? `Your weak topics — ${data.weakTopics.join(', ')} — suggest some conceptual gaps that are worth addressing now rather than later.` : 'No weak topics this time around — impressive!'} ${data.strongTopics.length > 0 ? `Strong topics like ${data.strongTopics.join(' and ')} show you\'re building a reliable knowledge base.` : ''} In interviews, it\'s not just what you know but how quickly you recall it — keep practicing under time pressure.`,

  (data) => `A score of ${data.percentage}% in a mixed-subject quiz is ${data.percentage >= 70 ? 'commendable' : 'a good starting point'}. ${data.strongTopics.length > 0 ? `You demonstrated clear strength in ${data.strongTopics.join(' and ')}.` : 'Aim to develop at least two strong subject areas.'} ${data.weakTopics.length > 0 ? `Allocate dedicated study time to ${data.weakTopics.join(', ')} before your next attempt.` : 'No weak areas detected — well balanced performance!'} Interview preparation is a marathon, not a sprint — stay consistent.`,

  (data) => `You got ${data.score}/${data.totalQuestions} right this time. ${data.percentage >= 60 ? 'You\'re trending in the right direction.' : 'A lower score now means more room to improve before the real interview.'} ${data.weakTopics.length > 0 ? `Pay close attention to ${data.weakTopics.join(', ')} — these topics frequently appear in technical interviews.` : 'Great — no weak topics to report!'} ${data.strongTopics.length > 0 ? `Your strength in ${data.strongTopics[0]} is an asset — make sure to highlight it confidently in interviews.` : ''} Keep going!`,

  (data) => `${data.percentage}% this round — ${data.percentage >= 70 ? 'you\'re well above the average candidate score.' : 'targeted practice will get you above the 70% mark soon.'} ${data.strongTopics.length > 0 ? `Topics like ${data.strongTopics.join(', ')} are clearly in your comfort zone.` : 'Keep building your comfort zone one topic at a time.'} ${data.weakTopics.length > 0 ? `For ${data.weakTopics.join(' and ')}, try reviewing core definitions and then attempting practical questions.` : 'Clean performance across all topics!'} You\'re building the right habits for interview success.`,

  (data) => `Final tally: ${data.score} correct, ${data.totalQuestions - data.score} incorrect, ${data.percentage}% overall. ${data.strongTopics.length > 0 ? `Your grasp of ${data.strongTopics.join(', ')} would impress any interviewer.` : 'Work towards having at least one subject you can answer without hesitation.'} ${data.weakTopics.length > 0 ? `${data.weakTopics.join(', ')} are your focus areas for the next session — don\'t skip them.` : 'No weak areas — you\'re firing on all cylinders!'} Remember: interviewers value clarity of thought as much as correct answers.`,
];

export default feedtemp;